import { BASE_URL } from "../../components/api-docs/ApiDocComponents.jsx";
import {
	Users,
	Globe,
	Package,
	DollarSign,
	Server,
	Mail,
	ShoppingCart,
	CreditCard,
	Bug,
} from "lucide-react";

function q(apiKey) {
	return apiKey || "ADMIN_API_KEY";
}

export function buildAdminApiSections(user) {
	const key = q(user?.apiKey);

	return [
		{
			id: "admin-users",
			title: "User management — /users/*",
			icon: Users,
			description:
				"requireAdmin() — use an admin account apiKey.",
			endpoints: [
				{
					method: "GET",
					path: "/users/all",
					title: "List all users",
					description: "Returns every user record",
					icon: Users,
					params: [],
					response: {
						state: "200",
						data: [{ id: 1, name: "…", role: "user" }],
					},
					example: `curl "${BASE_URL}/users/all?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/users/:id",
					title: "Get user by id",
					description: "Fetch a single user",
					icon: Users,
					params: [
						{
							name: "id",
							type: "path",
							required: true,
							description: "User id",
							example: "1",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/users/1?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/users/create",
					title: "Create user",
					description: "Create a user via query parameters",
					icon: Users,
					params: [
						{
							name: "name",
							type: "string",
							required: true,
							description: "Display name",
						},
						{
							name: "password",
							type: "string",
							required: true,
							description: "Password",
						},
						{
							name: "email",
							type: "string",
							required: false,
							description: "Email",
						},
						{
							name: "role",
							type: "string",
							required: false,
							description: "user | admin",
							example: "user",
						},
						{
							name: "balance",
							type: "number",
							required: false,
							description: "Initial balance",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/users/create?apiKey=${key}&name=demo&password=secret&email=a@b.com&role=user&balance=0"`,
				},
				{
					method: "GET",
					path: "/users/update/:id",
					title: "Update user",
					description: "Optional fields passed as query params",
					icon: Users,
					params: [
						{
							name: "id",
							type: "path",
							required: true,
							description: "User id",
						},
					],
					response: { state: "200", message: "User updated" },
					example: `curl "${BASE_URL}/users/update/1?apiKey=${key}&balance=100"`,
				},
				{
					method: "GET",
					path: "/users/delete",
					title: "Delete user",
					description: "Query: id",
					icon: Users,
					params: [
						{
							name: "id",
							type: "string",
							required: true,
							description: "User id",
						},
					],
					response: { state: "200", message: "User deleted successfully" },
					example: `curl "${BASE_URL}/users/delete?apiKey=${key}&id=1"`,
				},
			],
		},
		{
			id: "admin-country-service",
			title: "Countries & services — /country/* & /service/*",
			icon: Globe,
			description:
				"Sensitive writes — requireAdmin() and apiKey.",
			endpoints: [
				{
					method: "GET",
					path: "/country/create",
					title: "Create country",
					description: "Optional provider1 / provider2",
					icon: Globe,
					params: [
						{
							name: "country",
							type: "string",
							required: true,
							description: "Country name",
						},
						{
							name: "code_country",
							type: "string",
							required: true,
							description: "Country code",
						},
						{
							name: "provider1",
							type: "string",
							required: false,
							description: "Provider 1 id",
						},
						{
							name: "provider2",
							type: "string",
							required: false,
							description: "Provider 2 id",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/country/create?apiKey=${key}&country=US&code_country=1"`,
				},
				{
					method: "GET",
					path: "/country/update",
					title: "Update country",
					description:
						"Query: id, country, code_country, provider1, provider2",
					icon: Globe,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/country/update?apiKey=${key}&id=1&country=US&code_country=1&provider1=x&provider2=y"`,
				},
				{
					method: "GET",
					path: "/country/remove",
					title: "Delete country",
					description: "Query: id",
					icon: Globe,
					params: [
						{
							name: "id",
							type: "string",
							required: true,
							description: "Country id",
						},
					],
					response: { state: "200", data: null },
					example: `curl "${BASE_URL}/country/remove?apiKey=${key}&id=1"`,
				},
				{
					method: "GET",
					path: "/service/create",
					title: "Create service",
					description:
						"Query: servicename, code, provider1, provider2",
					icon: Package,
					params: [],
					response: { state: "201", data: {} },
					example: `curl "${BASE_URL}/service/create?apiKey=${key}&servicename=WhatsApp&code=wa&provider1=a&provider2=b"`,
				},
				{
					method: "GET",
					path: "/service/update",
					title: "Update service",
					description:
						"Query: id, servicename, code, provider1, provider2",
					icon: Package,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/service/update?apiKey=${key}&id=1&servicename=WhatsApp&code=wa"`,
				},
			],
		},
		{
			id: "admin-pricing",
			title: "Pricing — /pricing/*",
			icon: DollarSign,
			description: "Create, update, and remove pricing rows",
			endpoints: [
				{
					method: "GET",
					path: "/pricing/create",
					title: "Create pricing row",
					description:
						"countryId, serviceId, priceProvider1, priceProvider2",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/pricing/create?apiKey=${key}&countryId=1&serviceId=2&priceProvider1=1.5&priceProvider2=2"`,
				},
				{
					method: "GET",
					path: "/pricing/update",
					title: "Update pricing row",
					description:
						"Query: id and priceProvider1 and/or priceProvider2",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/pricing/update?apiKey=${key}&id=1&priceProvider1=2"`,
				},
				{
					method: "GET",
					path: "/pricing/remove",
					title: "Delete pricing row",
					description: "Query: id",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/pricing/remove?apiKey=${key}&id=1"`,
				},
			],
		},
		{
			id: "admin-provider3",
			title: "Provider 3 — admin",
			icon: Server,
			description:
				"`p3_countries` / `p3_services` — config `countryId` / `serviceId` are P3 table ids.",
			endpoints: [
				{
					method: "GET",
					path: "/provider3/access-sync",
					title: "Sync access for one service",
					description:
						"serviceCode must exist in p3_services; optional interval, serviceName",
					icon: Server,
					params: [
						{
							name: "serviceCode",
							type: "string",
							required: true,
							description: "Service code",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/provider3/access-sync?apiKey=${key}&serviceCode=wa&interval=30min"`,
				},
				{
					method: "GET",
					path: "/provider3/access-sync-all",
					title: "Full Provider 3 sync",
					description: "May return 409 if a sync is already running",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/provider3/access-sync-all?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/country-create",
					title: "Create P3 country",
					description: "Query: country, code_country",
					icon: Globe,
					params: [],
					response: {
						state: "201",
						data: {
							name: "Italy",
							code_country: "IT",
							id: 1,
						},
					},
					example: `curl "${BASE_URL}/provider3/admin/country-create?apiKey=${key}&country=Italy&code_country=IT"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/service-create",
					title: "Create P3 service",
					description: "servicename, code",
					icon: Package,
					params: [],
					response: {
						state: "201",
						data: {
							name: "WhatsApp",
							code: "wa",
							id: 2,
						},
					},
					example: `curl "${BASE_URL}/provider3/admin/service-create?apiKey=${key}&servicename=WhatsApp&code=wa"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/p3-catalog-countries",
					title: "All P3 countries (full catalog)",
					description: "All rows in p3_countries",
					icon: Globe,
					params: [],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/provider3/admin/p3-catalog-countries?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/p3-catalog-services",
					title: "All P3 services (full catalog)",
					description: "All rows in p3_services",
					icon: Package,
					params: [],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/provider3/admin/p3-catalog-services?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/provider3/config",
					title: "List Provider 3 config rows",
					description: "Pricing rows with p3Country / p3Service",
					icon: Server,
					params: [],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/provider3/config?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/provider3/config/create",
					title: "Create Provider 3 config row",
					description:
						"countryId & serviceId from P3 tables; price, upstream…",
					icon: Server,
					params: [],
					response: { state: "201", data: {} },
					example: `curl "${BASE_URL}/provider3/config/create?apiKey=${key}&countryId=1&serviceId=2&price=1.5&upstreamCountryCode=IT&upstreamServiceName=WhatsApp"`,
				},
				{
					method: "GET",
					path: "/provider3/config/update",
					title: "Update Provider 3 config row",
					description: "id and optional fields",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/provider3/config/update?apiKey=${key}&id=1&price=2"`,
				},
				{
					method: "GET",
					path: "/provider3/config/remove",
					title: "Delete Provider 3 config row",
					description: "Query: id",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/provider3/config/remove?apiKey=${key}&id=1"`,
				},
			],
		},
		{
			id: "admin-email-api",
			title: "Email admin — /email-admin/*",
			icon: Mail,
			description:
				"requireUser() then admin check in handler — send admin apiKey.",
			endpoints: [
				{
					method: "GET",
					path: "/email-admin/sites",
					title: "List email sites",
					description: "Full list (admin)",
					icon: Mail,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
							example: key,
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/sites?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/sites/create",
					title: "Create email site",
					description: "Additional params (name, status, …)",
					icon: Mail,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/email-admin/sites/create?apiKey=${key}&name=Example"`,
				},
				{
					method: "GET",
					path: "/email-admin/domains",
					title: "List domains",
					icon: Mail,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/domains?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/prices",
					title: "List prices",
					icon: DollarSign,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/prices?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/sync-availability",
					title: "Sync availability",
					description: "Manual sync",
					icon: Mail,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/email-admin/sync-availability?apiKey=${key}"`,
				},
			],
		},
		{
			id: "admin-order-ops",
			title: "Orders — maintenance & debug",
			icon: ShoppingCart,
			description: "`/order/*` — refunds, eligibility, debug tools",
			endpoints: [
				{
					method: "GET",
					path: "/order/process-refunds",
					title: "Process pending refunds",
					description: "Admin apiKey",
					icon: ShoppingCart,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
							example: key,
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/process-refunds?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/refund-eligible",
					title: "Orders eligible for refund",
					icon: ShoppingCart,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/order/refund-eligible?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/expire-orders",
					title: "Trigger order expiration (debug)",
					icon: Bug,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/expire-orders?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/expiration-status",
					title: "Order expiration status",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/expiration-status?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/cache-stats",
					title: "Cache statistics",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/cache-stats?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/background-status",
					title: "Background jobs status",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/background-status?apiKey=${key}"`,
				},
			],
		},
		{
			id: "admin-heleket",
			title: "Heleket — /payment/heleket/*",
			icon: CreditCard,
			description: "Admin Heleket invoices — admin apiKey",
			endpoints: [
				{
					method: "GET",
					path: "/payment/heleket/all",
					title: "All Heleket invoices",
					description: "requireApiKey with admin role",
					icon: CreditCard,
					params: [],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/payment/heleket/all?apiKey=${key}"`,
				},
			],
		},
	];
}
