import { BASE_URL } from "../../components/api-docs/ApiDocComponents.jsx";
import {
	Users,
	Globe,
	Package,
	DollarSign,
	Server,
	Mail,
	ShoppingCart,
	CreditCard,
	Bug,
} from "lucide-react";

function q(apiKey) {
	return apiKey || "ADMIN_API_KEY";
}

export function buildAdminApiSections(user) {
	const key = q(user?.apiKey);

	return [
		{
			id: "admin-users",
			title: "User management (admin)",
			icon: Users,
			description:
				"`/users/*` routes — require an admin account (JWT or admin apiKey)",
			endpoints: [
				{
					method: "GET",
					path: "/users/all",
					title: "List all users",
					description: "Returns every user record",
					icon: Users,
					params: [],
					response: {
						state: "200",
						data: [{ id: 1, name: "…", role: "user" }],
					},
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/users/all"`,
				},
				{
					method: "GET",
					path: "/users/:id",
					title: "Get user by id",
					description: "Fetch a single user",
					icon: Users,
					params: [
						{
							name: "id",
							type: "path",
							required: true,
							description: "User id",
							example: "1",
						},
					],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/users/1"`,
				},
				{
					method: "GET",
					path: "/users/create",
					title: "Create user",
					description: "Create a user via query parameters",
					icon: Users,
					params: [
						{
							name: "name",
							type: "string",
							required: true,
							description: "Display name",
						},
						{
							name: "password",
							type: "string",
							required: true,
							description: "Password",
						},
						{
							name: "email",
							type: "string",
							required: false,
							description: "Email",
						},
						{
							name: "role",
							type: "string",
							required: false,
							description: "user | admin",
							example: "user",
						},
						{
							name: "balance",
							type: "number",
							required: false,
							description: "Initial balance",
						},
					],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/users/create?name=demo&password=secret&email=a@b.com&role=user&balance=0"`,
				},
				{
					method: "GET",
					path: "/users/update/:id",
					title: "Update user",
					description: "Optional fields passed as query params",
					icon: Users,
					params: [
						{
							name: "id",
							type: "path",
							required: true,
							description: "User id",
						},
					],
					response: { state: "200", message: "User updated" },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/users/update/1?balance=100"`,
				},
				{
					method: "GET",
					path: "/users/delete",
					title: "Delete user",
					description: "Query: id",
					icon: Users,
					params: [
						{
							name: "id",
							type: "string",
							required: true,
							description: "User id",
						},
					],
					response: { state: "200", message: "User deleted successfully" },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/users/delete?id=1"`,
				},
			],
		},
		{
			id: "admin-country-service",
			title: "Countries & services (admin)",
			icon: Globe,
			description:
				"`/country/*` and `/service/*` — sensitive writes require admin",
			endpoints: [
				{
					method: "GET",
					path: "/country/create",
					title: "Create country",
					description: "Optional provider1 / provider2",
					icon: Globe,
					params: [
						{
							name: "country",
							type: "string",
							required: true,
							description: "Country name",
						},
						{
							name: "code_country",
							type: "string",
							required: true,
							description: "Country code",
						},
						{
							name: "provider1",
							type: "string",
							required: false,
							description: "Provider 1 id",
						},
						{
							name: "provider2",
							type: "string",
							required: false,
							description: "Provider 2 id",
						},
					],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/country/create?country=US&code_country=1"`,
				},
				{
					method: "GET",
					path: "/country/update",
					title: "Update country",
					description: "Query: id, country, code_country, provider1, provider2",
					icon: Globe,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/country/update?id=1&country=US&code_country=1&provider1=x&provider2=y"`,
				},
				{
					method: "GET",
					path: "/country/remove",
					title: "Delete country",
					description: "Query: id",
					icon: Globe,
					params: [
						{
							name: "id",
							type: "string",
							required: true,
							description: "Country id",
						},
					],
					response: { state: "200", data: null },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/country/remove?id=1"`,
				},
				{
					method: "GET",
					path: "/service/create",
					title: "Create service",
					description: "Query: servicename, code, provider1, provider2",
					icon: Package,
					params: [],
					response: { state: "201", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/service/create?servicename=WhatsApp&code=wa&provider1=a&provider2=b"`,
				},
				{
					method: "GET",
					path: "/service/update",
					title: "Update service",
					description: "Query: id, servicename, code, provider1, provider2",
					icon: Package,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/service/update?id=1&servicename=WhatsApp&code=wa"`,
				},
			],
		},
		{
			id: "admin-pricing",
			title: "Country / service pricing (admin)",
			icon: DollarSign,
			description: "`/pricing/*` create, update, and remove",
			endpoints: [
				{
					method: "GET",
					path: "/pricing/create",
					title: "Create pricing row",
					description:
						"countryId, serviceId, priceProvider1, priceProvider2",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/pricing/create?countryId=1&serviceId=2&priceProvider1=1.5&priceProvider2=2"`,
				},
				{
					method: "GET",
					path: "/pricing/update",
					title: "Update pricing row",
					description: "Query: id and priceProvider1 and/or priceProvider2",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/pricing/update?id=1&priceProvider1=2"`,
				},
				{
					method: "GET",
					path: "/pricing/remove",
					title: "Delete pricing row",
					description: "Query: id",
					icon: DollarSign,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/pricing/remove?id=1"`,
				},
			],
		},
		{
			id: "admin-provider3",
			title: "Provider 3 — admin",
			icon: Server,
			description:
				"`/provider3/*` sync, configuration, and quick-create helpers",
			endpoints: [
				{
					method: "GET",
					path: "/provider3/access-sync",
					title: "Sync access for one service",
					description: "serviceCode, interval, optional serviceName",
					icon: Server,
					params: [
						{
							name: "serviceCode",
							type: "string",
							required: true,
							description: "Service code",
						},
					],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/access-sync?serviceCode=telegram"`,
				},
				{
					method: "GET",
					path: "/provider3/access-sync-all",
					title: "Full Provider 3 sync",
					description: "May return 409 if a sync is already running",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/access-sync-all"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/country-create",
					title: "Create country (P3-only path)",
					description: "No P1/P2 fields — country, code_country",
					icon: Globe,
					params: [],
					response: { state: "201", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/admin/country-create?country=X&code_country=xx"`,
				},
				{
					method: "GET",
					path: "/provider3/admin/service-create",
					title: "Create service (P3-only path)",
					description: "servicename, code",
					icon: Package,
					params: [],
					response: { state: "201", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/admin/service-create?servicename=X&code=x"`,
				},
				{
					method: "GET",
					path: "/provider3/config",
					title: "List Provider 3 config rows",
					description: "All rows with relations",
					icon: Server,
					params: [],
					response: { state: "200", data: [] },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/config"`,
				},
				{
					method: "GET",
					path: "/provider3/config/create",
					title: "Create Provider 3 config row",
					description:
						"countryId, serviceId, price, upstreamCountryCode, upstreamServiceName",
					icon: Server,
					params: [],
					response: { state: "201", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/config/create?countryId=1&serviceId=2&price=1&upstreamCountryCode=us&upstreamServiceName=telegram"`,
				},
				{
					method: "GET",
					path: "/provider3/config/update",
					title: "Update Provider 3 config row",
					description: "id and optional price, upstreamCountryCode, upstreamServiceName",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/config/update?id=1&price=2"`,
				},
				{
					method: "GET",
					path: "/provider3/config/remove",
					title: "Delete Provider 3 config row",
					description: "Query: id",
					icon: Server,
					params: [],
					response: { state: "200", data: {} },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/provider3/config/remove?id=1"`,
				},
			],
		},
		{
			id: "admin-email-api",
			title: "Email admin API",
			icon: Mail,
			description:
				"Prefix `/email-admin/` — requires JWT or admin apiKey; several handlers validate `apiKey` in the query string.",
			endpoints: [
				{
					method: "GET",
					path: "/email-admin/sites",
					title: "List email sites",
					description: "Full list (admin) — `apiKey` required for the admin check",
					icon: Mail,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
							example: key,
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/sites?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/sites/create",
					title: "Create email site",
					description: "Additional params per API (name, status, …)",
					icon: Mail,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/email-admin/sites/create?apiKey=${key}&name=Example"`,
				},
				{
					method: "GET",
					path: "/email-admin/domains",
					title: "List domains",
					icon: Mail,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/domains?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/prices",
					title: "List prices",
					icon: DollarSign,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/email-admin/prices?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/email-admin/sync-availability",
					title: "Sync email availability",
					description: "Manual sync of account availability",
					icon: Mail,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/email-admin/sync-availability?apiKey=${key}"`,
				},
			],
		},
		{
			id: "admin-order-ops",
			title: "Orders — admin & debug",
			icon: ShoppingCart,
			description: "`/order/*` refunds, maintenance, and debug helpers",
			endpoints: [
				{
					method: "GET",
					path: "/order/process-refunds",
					title: "Process pending refunds",
					description: "Requires admin apiKey in the request",
					icon: ShoppingCart,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
							example: key,
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/process-refunds?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/refund-eligible",
					title: "Orders eligible for refund",
					icon: ShoppingCart,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: [] },
					example: `curl "${BASE_URL}/order/refund-eligible?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/expire-orders",
					title: "Trigger order expiration (debug)",
					icon: Bug,
					params: [
						{
							name: "apiKey",
							type: "string",
							required: true,
							description: "Admin API key",
						},
					],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/expire-orders?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/expiration-status",
					title: "Order expiration status",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/expiration-status?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/cache-stats",
					title: "Cache statistics",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/cache-stats?apiKey=${key}"`,
				},
				{
					method: "GET",
					path: "/order/debug/background-status",
					title: "Background jobs status",
					icon: Bug,
					params: [],
					response: { state: "200", data: {} },
					example: `curl "${BASE_URL}/order/debug/background-status?apiKey=${key}"`,
				},
			],
		},
		{
			id: "admin-heleket",
			title: "Heleket payments (admin)",
			icon: CreditCard,
			description: "Prefix `/payment/heleket/`",
			endpoints: [
				{
					method: "GET",
					path: "/payment/heleket/all",
					title: "All Heleket invoices",
					description: "Admin-only route (JWT or admin apiKey)",
					icon: CreditCard,
					params: [],
					response: { state: "200", data: [] },
					example: `curl -H "Authorization: Bearer <token>" "${BASE_URL}/payment/heleket/all"`,
				},
			],
		},
	];
}
